### ISSUE TITLE
Gradio GPU 사용 관련 이슈

### ISSUE THREAD

**Issue by shiningstone23** [OpenXAIProject/pnpxai#142]
Gradio에서 제공하는 GPU를 쓸 때 Optimize에서 이런 에러가 나는데, 혹시 짐작 가는 바가 있으신지 여쭤봅니다
(저희 서버에서 돌리면 정상적으로 작동하는 것을 보아 Gradio의 dependency가 있는 것 같습니다)

Norm.__init__이라는 함수를 pickle할 때 lambda 함수를 사용하는 부분이 있어 에러가 나는 것 같습니다. Gradio에서 쓸 때는 Norm이라는 함수 안에 lambda를 없애고 싶은데, 어디에서 쓰이는지 모르겠네요.(pickle을 쓰는 이유는 Gradio는 GPU를 쓸 때 특정 함수에 annotation을 달아두면 이를 wrapping해서 실행하는 방식인데, 이 과정에서 pickle이 쓰이지 않을까 추측하고 있습니다.)

이 링크(https://github.com/gradio-app/gradio/issues/8844)는 제가 찾은 유사한 에러 사례입니다.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spaces/utils.py", line 43, in put
    super().put(obj)
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'Norm.__init__.<locals>.<lambda>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/spaces/zero/wrappers.py", line 202, in gradio_handler
    worker.arg_queue.put(((args, kwargs), GradioPartialContext.get()))
  File "/usr/local/lib/python3.10/site-packages/spaces/utils.py", line 51, in put
    raise PicklingError(message)
_pickle.PicklingError: Can't pickle local object 'Norm.__init__.<locals>.<lambda>'`

**Comment by shiningstone23** [comment]
Solved
Do not use @space.GPU on the method of class. Only for the function. Though the reason why this makes Pickling error is not clear, but it solved
