### ISSUE TITLE
Compatibility with transformers.ResNetForImageClassification

### ISSUE THREAD

**Issue by wltjr1007** [OpenXAIProject/pnpxai#156]
Minimal, reproducible example:
https://colab.research.google.com/drive/1ucUpr-PJFS2JQJ-9T5ziCKXlxcz7A2E8?usp=sharing

I am getting the following error with `transformers.ResNetForImageClassification`. Seems like the error happens only for GradCAM and GuidedGradCam.

```
ERR GradCam
Traceback (most recent call last):
  File "<ipython-input-10-db9ca3d8f319>", line 10, in <cell line: 7>
    explanations[name] = explainer.attribute(inputs, labels)
  File "/content/pnpxai/pnpxai/explainers/grad_cam.py", line 29, in attribute
    layer = find_cam_target_layer(self.model)
  File "/content/pnpxai/pnpxai/explainers/utils/utils.py", line 15, in find_cam_target_layer
    traced_model = symbolic_trace(model)
  File "/content/pnpxai/pnpxai/core/detector/detector.py", line 42, in symbolic_trace
    graph = tracer.trace(model)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/_symbolic_trace.py", line 823, in trace
    (self.create_arg(fn(*args)),),
  File "<ipython-input-5-df7d3287eee8>", line 207, in forward
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/proxy.py", line 456, in __iter__
    return self.tracer.iter(self)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/proxy.py", line 327, in iter
    raise TraceError('Proxy object cannot be iterated. This can be '
torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors

ERR GuidedGradCam
Traceback (most recent call last):
  File "<ipython-input-10-db9ca3d8f319>", line 10, in <cell line: 7>
    explanations[name] = explainer.attribute(inputs, labels)
  File "/content/pnpxai/pnpxai/explainers/guided_grad_cam.py", line 30, in attribute
    layer = find_cam_target_layer(self.model)
  File "/content/pnpxai/pnpxai/explainers/utils/utils.py", line 15, in find_cam_target_layer
    traced_model = symbolic_trace(model)
  File "/content/pnpxai/pnpxai/core/detector/detector.py", line 42, in symbolic_trace
    graph = tracer.trace(model)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/_symbolic_trace.py", line 823, in trace
    (self.create_arg(fn(*args)),),
  File "<ipython-input-5-df7d3287eee8>", line 207, in forward
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/proxy.py", line 456, in __iter__
    return self.tracer.iter(self)
  File "/usr/local/lib/python3.10/dist-packages/torch/fx/proxy.py", line 327, in iter
    raise TraceError('Proxy object cannot be iterated. This can be '
torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors
```

**Comment by ghkim9213** [comment]
Hello @wltjr1007, thank you for reporting the issues. Please let me briefly explain why your error happens and how the latest PR fix it.

### Why the error happens

Your error happens because our CAM-based explainers try to automatically find cam target layer using `torch.fx.symbolic_trace` which requires explicit symbol, instead of `*args` or `**kwargs`, as arguments of `forward` method. For example,
```python
class YourModel(YourModelBase):
#    def forward(self, *args, **kwargs):
#        return super().forward(*args, **kwargs)
    def forward(self, pixel_values):
        return super().forward(pixel_values)
```
By the way, this kind of correction may also not work because `symbolic_trace` requires more rigorous style to the model's `forward` method e.g. it does not allow dynamic control in the method such as `if-else`. Unfortunately, `transformers.ResNetForImageClassification` does not satisfy the condition.

### How the latest PR fix it

I simply added `set_target_layer` method to the CAM-based explainers and validations for it. In your case, now, you can manually set the target layer as followings:
 
```python
explainer = GradCam(model)
attrs = explainer.set_target_layer(model.resnet.encoder).attribute(inputs, labels)
```

Thank you once again for the reporting issues.
